sudo: false

language: node_js

node_js:
  - "6"

before_install:
  - npm install -g npm@5
  - npm install -g gulp-cli

install:
  - npm install

script: gulp travis

cache:
  directories:
    - "node_modules"